name: Build and Deploy
on:
  push:
    branches:
      - main
    # Anytime a pattern matches the tags-ignore pattern, the workflow will not run
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-branches-and-tags
    tags-ignore:
      - '*.*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      # checkout and get semantic info
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get semantic release info
        id: semantic_release_info
        uses: jossef/action-semantic-release-info@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      # Update files with new version info and release urls
      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: Modpack/manifest.json
          field: version
          value: ${{ steps.semantic_release_info.outputs.git_tag }}
      - name: Update server.properties version
        run: sed -i "s|\(^motd=\).*|\1 Minecraft CRAP ${{ steps.semantic_release_info.outputs.git_tag }}|" Serverpack/server.properties

      # Commit and push file changes
      - name: Commit files and create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "docs(): bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
          git tag ${{ steps.semantic_release_info.outputs.git_tag }}
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}
          tags: true
      
      # Create zip files for release
      - name: Zip Release Modpack
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: modpack-${{ steps.semantic_release_info.outputs.git_tag }}.zip
          path: .
          directory: Modpack
      - name: Zip Release Serverpack
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: serverpack-${{ steps.semantic_release_info.outputs.git_tag }}.zip
          path: .
          directory: Serverpack
          
      # use created zip files for release
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "Modpack/modpack-${{ steps.semantic_release_info.outputs.git_tag }}.zip,Serverpack/serverpack-${{ steps.semantic_release_info.outputs.git_tag }}.zip"
            tag: ${{ steps.semantic_release_info.outputs.git_tag }}
            body: ${{ steps.semantic_release_info.outputs.notes }}
            token: ${{ github.token }}
